### ISSUE TITLE
Is this a joke?

### ISSUE THREAD

**Issue by MrManny** [Xotic750/is-truthy-x#1]
I mean, what this library do that vanilla ECMAScript doesn't already do implicitly through type coercion? Additionally, there have been 7 "releases" already, yet the only highly trivial source file for this repository has been touched exactly once.

**Comment by Xotic750** [comment]
@MrManny Well, you can't run coercive code implicitly as as a callback, it has to be a function. However, you can use the constructor `Boolean`, which this project essentially is but with a more descriptive name. The number of releases are due to an automated script that I am writing, and sure, I have not got that script perfect on the first attempt/run hence the number of minor releases. At some point this project will cease to be, but not yet. Hopefully you feel a little more educated by this information.
